name: Automation tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GH_PACKAGE_TOKEN:
        required: true
env:
  GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
jobs:
  test:
    timeout-minutes: 60
    runs-on: self-hosted-main
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - run: |
        echo $GH_PACKAGE_TOKEN
        ls | grep package-lock.json
        npm ci --ignore-scripts
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30